### ISSUE TITLE
Verify merge

### ISSUE THREAD

**Issue by dukedhx** [dukedhx/DefinitelyTyped#1]
Need Alan to validate the merge before we can publish: commit b779df6cf465ce51f159e95c7221a2ebe371dd6c

**Comment by dukedhx** [comment]
Need Alan to verify that the merging of his definitions is complete w/o loose ends

**Comment by dukedhx** [comment]
Need Alan @alansmithnbs  to validate the merge before we can publish: commit https://github.com/dukedhx/DefinitelyTyped/commit/b779df6cf465ce51f159e95c7221a2ebe371dd6c

**Comment by alansmithnbs** [comment]
@dukedhx I replaced the typings in a branch of my Angular components and all looks really good to me. Fantastic work! 👍

**Comment by dukedhx** [comment]
Tks Alan! PR to publish on its way!
